### ISSUE TITLE
Catch SIGTERM signal to gracefully terminate

### ISSUE THREAD

**Issue by pataquets** [hgoebl/nerdshow#2]
While dockerizing the app, I've found that it ignores ```SIGTERM``` signals from both ```CTRL+C``` and ```docker stop``` commands (it just gets killed after 10 seconds in the later case).
Trapping ```SIGTERM``` signal to terminate gracefully would prevent this annoyance.
Thank you for this useful app.

**Comment by hgoebl** [comment]
I tried to manage this, but without success. Seams like Socket.IO is a bit nasty when an immediate shutdown is desired. If you want, you can try with branch https://github.com/hgoebl/nerdshow/tree/0.5.0-sigterm-and-upgrade-dep and create PR then. Don't have enough time currently.

**Comment by pataquets** [comment]
Tested it and works OK, thank you.
Successfully viewed "About" demo slideshow and used remote without problem.
Excerpt from stdout:
´´´
Starting src_app_1
Attaching to src_app_1
app_1  | No argument given for folder - taking examples...
app_1  | Express serving `nerdshow` at http://localhost:8008/
app_1  | Process ID: 1
app_1  | Serving files in /usr/src/app/examples
app_1  | Socket connected! id: IJLvPL_ENvRnqJFdAAAA
app_1  | Socket connected! id: n7IyzoaLD_eRuFBsAAAB
app_1  | SIGTERM received, shutting down...
app_1  | express closed
app_1  | io closed
src_app_1 exited with code 0
```
PR sent as instructed.

**Comment by hgoebl** [comment]
Thanks for contributing @pataquets 
npm published minutes ago.
